# For help and support visit please: http://bit.ly/bogbukkitdev or http://bit.ly/bogbukkit
permissions: true
botanical: true
blocks:
  glass: true
  ice: true
  leaves: true
  fence: true
  netherfence: true
  glowstone: true
  tnt: false
  stairs:
    wood: true
    stone: true
    cobblestone: true
    brick: true
    netherbrick: true
  cactus: false
  steps: true
  ironfence: true
  thinglass: true