# For help and support visit please: http://bit.ly/bogbukkitdev or http://bit.ly/bogbukkit
tweaks:
  fencefix: true
permissions: true
blocks:
  glass: true
  ice: true
  leaves: true
  fence: true
  netherfence: true
  glowstone: true
  tnt: false